export const ui = {
    titleEl: document.getElementById("page-title"),                     // 
    contentEl: document.getElementById("content"),                      // 
    createPartyBtn: document.getElementById("create-party-btn"),        // 
    joinPartyBtn: document.getElementById("join-party-btn"),            // 
    partyCodeInput: document.getElementById("party-code-input"),        // 
    partyCodeEl: document.getElementById("party-code"),                 // 
    partyCodeDisplay: document.getElementById("party-code-display"),    // 
    startGameBtn: document.getElementById("start-game-btn"),            // 
    partyLobbyModal: document.getElementById("party-lobby-modal"),      // 
    startHeader: document.getElementById("start-header"),               // 
    partyGamemodeSelect: document.getElementById("party-gamemode"),     // 
    clickCounterEl: document.getElementById("click-counter"),           // 
    winTitleEl: document.getElementById("win-title"),                   // 
    timerEl: document.getElementById("timer"),                         // 
    timerDisplay: document.getElementById("timer-display"),             // 
    startPageEl: document.getElementById("start-page"),                 // 
    targetPageEl: document.getElementById("target-page"),               // 
    startModal: document.getElementById("start-modal"),                 // 
    startPageInput: document.getElementById("start-menu"),              // 
    targetPageInput: document.getElementById("target-menu"),            // 
    startForm: document.getElementById("start-form"),                   // 
    langSelect: document.getElementById("wiki-lang"),                   // 
    gamemodeSelect: document.getElementById("gamemode"),                // 
    tooltip: document.getElementById("target-tooltip"),                 // 
    homeBtn: document.getElementById("home-btn"),                       // 
    winModal: document.getElementById("win-modal"),                     // 
    finalClicksEl: document.getElementById("final-clicks"),             // 
    finalTimeEl: document.getElementById("final-time"),                 // 
    newRoundBtn: document.getElementById("new-round-btn"),              // 
}